/******************************************
* VersionInfo Resource include file
* by LuoYunBin
******************************************/
#define	VS_VERSION_INFO			1
#define	VS_USER_DEFINED			100
#define	VS_FFI_SIGNATURE		0x0FEEF04BD
#define	VS_FFI_STRUCVERSION		0x10000
#define	VS_FFI_FILEFLAGSMASK	0x3F
#define	VS_FF_DEBUG				1
#define	VS_FF_PRERELEASE		2
#define	VS_FF_PATCHED			4
#define	VS_FF_PRIVATEBUILD		8
#define	VS_FF_INFOINFERRED		0x10
#define	VS_FF_SPECIALBUILD		0x20
#define	VOS_UNKNOWN				0
#define	VOS_DOS					0x10000
#define	VOS_OS216				0x20000
#define	VOS_OS232				0x30000
#define	VOS_NT					0x40000
#define	VOS_BASE				0
#define	VOS_WINDOWS16			1
#define	VOS_PM16				2
#define	VOS_PM32				3
#define	VOS_WINDOWS32			4
#define	VOS_DOS_WINDOWS16		0x10001
#define	VOS_DOS_WINDOWS32		0x10004
#define	VOS_OS216_PM16			0x20002
#define	VOS_OS232_PM32			0x30003
#define	VOS_NT_WINDOWS32		0x40004
#define	VFT_UNKNOWN				0
#define	VFT_APP					1
#define	VFT_DLL					2
#define	VFT_DRV					3
#define	VFT_FONT				4
#define	VFT_VXD					5
#define	VFT_STATIC_LIB			7
#define	VFT2_UNKNOWN			0
#define	VFT2_DRV_PRINTER		1
#define	VFT2_DRV_KEYBOARD		2
#define	VFT2_DRV_LANGUAGE		3
#define	VFT2_DRV_DISPLAY		4
#define	VFT2_DRV_MOUSE			5
#define	VFT2_DRV_NETWORK		6
#define	VFT2_DRV_SYSTEM			7
#define	VFT2_DRV_INSTALLABLE	8
#define	VFT2_DRV_SOUND			9
#define	VFT2_DRV_COMM			0x0A
#define	VFT2_DRV_INPUTMETHOD	0x0B
#define	VFT2_FONT_RASTER		1
#define	VFT2_FONT_VECTOR		2
#define	VFT2_FONT_TRUETYPE		3
